### ISSUE TITLE
DOS65 V3 for WC6502SXB

### ISSUE THREAD

**Issue by Java6502** [floobydust/DOS-65-V3.03-ROM#1]
Hello,
I am interested in getting DOS65 up and running on my WC65C02SXB.  It seems that Mr. Leary has created a ROM version with the WC65C02SXB board being one of the targets.   Reference your write up:

https://www.retrobrewcomputers.org/forum/index.php?t=msg&goto=9444&&srch=dos%2F65#msg_9444

I'm assuming that your V3.3 started with his V3.  Where can I obtain the V3 that can be built to run on the WC65C02SXB?  The source code for DOS65 seems to be scattered around all over the place, and so it's a bit tricky trying to figure out where to get started.  

I think what I'm looking for should be available at http://retro.hansotten.nl/6502-sbc/dos-65/

I downloaded the zip file dos652020 but everything seems to be designed to run on Daryl Rictor's SBC2.

Any help would be greatly appreciated.  I apologize for reaching out to you via this forum, however I could not obtain any contact info for you or Mr. Leary. 

Thanks,
Jonathan

**Comment by floobydust** [comment]
Hi Jonathan,

There should be some code in there that provides for the WDC board. Also note that there are details on how to do that in one of the PDFs, which also shows the schematic for the SD Card adapter. This adapter attaches to a VIA port, so much of the code between the two SBCs is common, sans the console side.

 Drop me an email at "kemaier2@bellsouth.net" and I can send you the original files that Richard sent me. Just a side note, Richard is mostly retired and has some health issues, so he's not really doing much with this anymore. He was extremely helpful to me when I first reached out to him over a year ago.

 Regards, KM
